name: Science News Bot

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:  # Ручной запуск

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install google-generativeai requests beautifulsoup4 lxml
    
    - name: Check Facts.txt
      run: |
        echo "📊 Финальная проверка Facts.txt:"
        echo "Размер: $(wc -c < Facts.txt) байт"
        md5sum Facts.txt
    
    - name: Create necessary directories
      run: |
        mkdir -p commentary
        echo "📁 Папка commentary создана"
    
    - name: Run Science News Bot
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        echo "=== Запуск основного скрипта ==="
        echo "📊 Финальная проверка Facts.txt:"
        echo "Размер: $(wc -c < Facts.txt) байт"
        md5sum Facts.txt
        python news_bot.py
    
    - name: Check created files
      run: |
        echo "📁 Проверяем созданные файлы:"
        ls -la
        echo "📁 Содержимое папки commentary:"
        ls -la commentary/ || echo "Папка commentary пуста или не существует"
        echo "📄 Проверяем processed_news.json:"
        if [ -f "processed_news.json" ]; then
          echo "✅ processed_news.json существует"
          wc -l processed_news.json
          head -5 processed_news.json
        else
          echo "❌ processed_news.json не найден"
        fi
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "📝 Нет изменений для коммита"
        else
          echo "📝 Коммитим новые файлы:"
          git status
          git commit -m "🤖 Добавлены новые комментарии Alexey Turchin ($(date '+%Y-%m-%d %H:%M'))"
          git push
          echo "✅ Файлы успешно сохранены в репозиторий!"
        fi
