name: Science News Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:  # Ручной запуск

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install google-generativeai requests beautifulsoup4 lxml
    
    - name: Check Facts.txt
      run: |
        echo "📊 Финальная проверка Facts.txt:"
        echo "Размер: $(wc -c < Facts.txt) байт"
        md5sum Facts.txt
    
    - name: Run Science News Bot
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        echo "=== Запуск основного скрипта ==="
        echo "📊 Финальная проверка Facts.txt:"
        echo "Размер: $(wc -c < Facts.txt) байт"
        md5sum Facts.txt
        python news_bot.py
